import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";
import { deletePayoutAccount, savePayoutAccount } from "@/app/actions/payouts";

export default async function PayoutsPage() {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) redirect("/login");
  const accounts = process.env.DATABASE_URL ? await db.sellerPayoutAccount.findMany({ where: { userId: session.user.id }, orderBy: { createdAt: "desc" } }) : [];

  return <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8"><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#f97316]">Seller account</p><h1 className="mt-3 text-4xl font-black tracking-[-0.06em] text-slate-900">Payout accounts</h1></div><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><form action={savePayoutAccount} className="space-y-4 rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-sm"><select name="method" className="w-full rounded-full border border-slate-200 bg-slate-50 px-4 py-3"><option value="BANK_ACCOUNT">Bank account / IBAN</option><option value="JAZZCASH">JazzCash</option></select><input name="accountName" required placeholder="Account holder name" className="w-full rounded-full border border-slate-200 bg-slate-50 px-4 py-3" /><input name="iban" placeholder="PK00ABCD..." className="w-full rounded-full border border-slate-200 bg-slate-50 px-4 py-3" /><input name="jazzCashPhone" placeholder="JazzCash number: 03XXXXXXXXX" className="w-full rounded-full border border-slate-200 bg-slate-50 px-4 py-3" /><button className="w-full rounded-full border border-slate-300 bg-white px-5 py-3 text-sm font-semibold uppercase tracking-[0.16em] text-slate-900">Save payout account</button></form><div className="space-y-4">{accounts.length ? accounts.map((account) => <div key={account.id} className="flex items-center justify-between rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-sm"><div><div className="text-xs font-semibold uppercase tracking-[0.2em] text-[#f97316]">{account.method === "BANK_ACCOUNT" ? "Bank account" : "JazzCash"}</div><h2 className="mt-2 text-xl font-black text-slate-900">{account.accountName}</h2><p className="mt-1 text-sm text-slate-600">{account.iban ?? account.jazzCashPhone}</p></div><form action={deletePayoutAccount}><input type="hidden" name="id" value={account.id} /><button className="text-sm text-slate-500 underline hover:text-red-600">Remove</button></form></div>) : <div className="rounded-[1.75rem] border border-dashed border-slate-300 bg-white p-10 text-center text-slate-600">No payout accounts saved yet.</div>}</div></div></div>;
}
