"use client";
import{useEffect,useMemo,useState}from"react";
type CjProduct={id:string,name?:string,sku?:string,image?:string,sellPrice?:number|string,nowPrice?:number|string,inventory?:number,category?:string,freeShipping?:boolean,deliveryCycle?:string};
export default function CjCatalogClient({supplierId}:{supplierId:string}){
 const[q,setQ]=useState(""),[country,setCountry]=useState(""),[products,setProducts]=useState<CjProduct[]>([]),[msg,setMsg]=useState(""),[loading,setLoading]=useState(false),[importing,setImporting]=useState(""),[syncing,setSyncing]=useState(""),[markup,setMarkup]=useState("30"),[sort,setSort]=useState("relevance"),[stockFilter,setStockFilter]=useState("all"),[shippingFilter,setShippingFilter]=useState("all"),[page,setPage]=useState(1),[totalPages,setTotalPages]=useState(1),[totalRecords,setTotalRecords]=useState(0),[categories,setCategories]=useState<any[]>([]),[categoryId,setCategoryId]=useState(""),[subcategoryId,setSubcategoryId]=useState("");
 useEffect(()=>{fetch("/api/admin/categories").then(r=>r.ok?r.json():null).then(j=>{if(j)setCategories(j.categories||[])}).catch(()=>{})},[]);
 const topCategories=useMemo(()=>categories.filter(c=>!c.parentId),[categories]);
 const subcategories=useMemo(()=>categories.filter(c=>c.parentId===categoryId),[categories,categoryId]);
 async function search(e?:any,nextPage=1){e?.preventDefault();setLoading(true);setMsg("");const params=new URLSearchParams({supplierId,size:"20",page:String(nextPage)});if(q.trim())params.set("keyword",q.trim());if(country)params.set("countryCode",country);const r=await fetch("/api/admin/suppliers/cj/products?"+params.toString());const j=await r.json();if(r.ok){setProducts(j.products||[]);setPage(j.page||nextPage);setTotalPages(j.totalPages||1);setTotalRecords(j.totalRecords||0)}else setMsg(j.error||"Unable to load CJ products.");setLoading(false)}
 async function importProduct(item:CjProduct){if(!window.confirm("Import this CJ product as a DRAFT into MOTEVRA?"))return;setImporting(item.id);setMsg("");try{const r=await fetch("/api/admin/suppliers/cj/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({supplierId,pid:item.id,markupPercent:Number(markup)})});const text=await r.text();let j:any={};try{j=JSON.parse(text)}catch{}if(r.ok){setMsg("Imported successfully as DRAFT. "+(j.importedVariants||0)+" variants created.");setProducts(x=>x.filter(p=>p.id!==item.id));setTotalRecords(x=>Math.max(0,x-1))}else setMsg(j.error||text||"Import failed. Check the server log.")}catch(e){setMsg(e instanceof Error?e.message:"Import request failed. Please try again.")}finally{setImporting("")}}
 async function syncProduct(item:CjProduct){if(!window.confirm("Sync this imported CJ product's latest inventory now?"))return;setSyncing(item.id);setMsg("");const r=await fetch("/api/admin/suppliers/cj/sync",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({supplierId,productId:item.id})});const j=await r.json();if(r.ok)setMsg("Inventory synchronized. "+j.totalStock+" total units across "+j.warehousesSynced+" warehouse(s).");else setMsg(j.error||"Inventory sync failed.");setSyncing("")}
 const visibleProducts=useMemo(()=>products.filter(p=>(stockFilter==="in"?Number(p.inventory||0)>0:stockFilter==="out"?Number(p.inventory||0)<=0:true)&&(shippingFilter==="free"?Boolean(p.freeShipping):true)).sort((a,b)=>{if(sort==="price-low")return Number(a.nowPrice??a.sellPrice??0)-Number(b.nowPrice??b.sellPrice??0);if(sort==="price-high")return Number(b.nowPrice??b.sellPrice??0)-Number(a.nowPrice??a.sellPrice??0);if(sort==="stock-high")return Number(b.inventory||0)-Number(a.inventory||0);return String(a.name||"").localeCompare(String(b.name||""))}),[products,sort,stockFilter,shippingFilter]);
 return <main className="section cj-catalog-page"><div className="container"><div className="admin-heading cj-catalog-heading"><div><p className="eyebrow">CJ DROPSHIPPING</p><h1>Product catalogue</h1><p className="hero-copy">Search CJ's live catalogue, preview products and import selected items as drafts.</p></div><a className="button button-dark" href="/admin/suppliers">Back to suppliers</a></div>
 <form className="cj-search-panel admin-card" onSubmit={e=>search(e,1)}><div className="cj-search-main"><label>Product search</label><div className="cj-search-input"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search product name, SKU or keyword"/></div></div><div className="cj-filter-field"><label>Warehouse</label><input value={country} onChange={e=>setCountry(e.target.value.toUpperCase())} maxLength={2} placeholder="CN"/></div><div className="cj-filter-field"><label>Motevra margin</label><input type="number" min="30" step="0.1" value={markup} onChange={e=>setMarkup(e.target.value)} placeholder="30%"/></div><button className="button button-dark cj-search-button" type="submit">{loading?"Searching…":"Search CJ"}</button></form>
 <div className="cj-toolbar"><div className="cj-toolbar-count">{totalRecords?totalRecords+" products found":"Search results"}</div><div className="cj-toolbar-filters"><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort products"><option value="relevance">Sort: Relevance</option><option value="price-low">Price: Low to high</option><option value="price-high">Price: High to low</option><option value="stock-high">Stock: High to low</option></select><select value={stockFilter} onChange={e=>setStockFilter(e.target.value)} aria-label="Filter stock"><option value="all">All stock</option><option value="in">In stock</option><option value="out">Out of stock</option></select><select value={shippingFilter} onChange={e=>setShippingFilter(e.target.value)} aria-label="Filter shipping"><option value="all">All shipping</option><option value="free">Free shipping</option></select></div></div>
 {msg&&<div className="admin-message cj-message">{msg}</div>}
 <section className="admin-card cj-results-card"><div className="cj-results-head"><div><span className="eyebrow">LIVE CATALOGUE</span><h2>Products</h2></div><span className="muted">{visibleProducts.length} shown</span></div>{!visibleProducts.length&&!loading?<div className="cj-empty"><strong>{products.length?"No products match these filters":"Search the CJ catalogue to start."}</strong><span>{products.length?"Try changing the stock or shipping filters.":"Use a product name, SKU or keyword above."}</span></div>:<div className="cj-product-grid">{visibleProducts.map(item=><article className="cj-product-card" key={item.id}><div className="cj-product-image">{item.image?<img src={item.image} alt={item.name||"CJ product"} loading="lazy"/>:<span>No image</span>}{item.freeShipping&&<b>FREE SHIPPING</b>}</div><div className="cj-product-body"><div className="cj-product-category">{item.category||"Uncategorized"}</div><h3>{item.name||"Unnamed CJ product"}</h3><div className="cj-product-meta"><span>SKU {item.sku||"—"}</span><span>{Number(item.inventory||0)} in stock</span></div><div className="cj-product-bottom"><strong>$ {item.nowPrice||item.sellPrice||"—"}</strong>{item.deliveryCycle&&<small>{item.deliveryCycle} delivery</small>}</div><div className="cj-product-actions"><button type="button" className="button button-small button-dark" onClick={()=>importProduct(item)} disabled={importing===item.id}>{importing===item.id?"Importing…":"Import as Draft"}</button><span className="cj-product-id">CJ {item.id}</span></div></div></article>)}</div>}{totalPages>1&&<div className="cj-pagination"><button className="button button-small" disabled={loading||page<=1} onClick={()=>search(undefined,page-1)}>Previous</button><span>Page {page} of {totalPages}</span><button className="button button-small" disabled={loading||page>=totalPages} onClick={()=>search(undefined,page+1)}>Next</button></div>}</section>
 <section className="admin-card cj-sync-card"><div><span className="eyebrow">INVENTORY</span><h2>Synchronize imported product</h2><p className="muted">Refresh CJ warehouse quantities and variant stock for an imported MOTEVRA product.</p></div><div className="admin-actions"><input placeholder="MOTEVRA product ID" id="cj-product-id"/><button className="button button-dark" disabled={syncing!==""} onClick={()=>{const id=(document.getElementById("cj-product-id") as HTMLInputElement)?.value.trim();if(id)syncProduct({id});else setMsg("Enter a MOTEVRA product ID.")}}>{syncing?"Syncing…":"Sync inventory"}</button></div></section>
 <section className="admin-card cj-note-card"><h2>Import behavior</h2><p className="muted">Imported products remain DRAFT for review. CJ supplier cost, variants, warehouse inventory and synchronization timestamps are stored separately from the customer-facing product.</p></section>
 </div></main>}
