"use client";
import{useEffect,useState}from"react";
const classes=["STANDARD","HEAVY","BATTERY","LIQUID","ELECTRONICS","TYRE","WHEEL","RESTRICTED"];
export default function ShippingSettingsClient(){
 const[d,setD]=useState<any>({countries:[],zones:[],taxes:[],suppliers:[]}),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true);
 const[s,setS]=useState<any>({zoneId:"",name:"Standard shipping",shippingClass:"",supplierId:"",price:"",currency:"USD",minWeight:"",maxWeight:"",minOrderValue:"",maxOrderValue:""});
 const[t,setT]=useState<any>({countryId:"",name:"Sales tax",rate:"",taxClass:""});
 async function load(){setLoading(true);const r=await fetch("/api/admin/commerce");const j=await r.json();if(r.ok)setD(j);else setMsg(j.error||"Unable to load.");setLoading(false)}
 useEffect(()=>{load()},[]);
 async function post(body:any){setMsg("Saving…");const r=await fetch("/api/admin/commerce",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();setMsg(r.ok?(j.message||"Saved."):(j.error||"Save failed."));if(r.ok)await load()}
 const field=(set:any,obj:any)=>(k:string)=>(e:any)=>set({...obj,[k]:e.target.value});
 return <main className="section"><div className="container">
  <div className="admin-heading"><div><p className="eyebrow">MOTEVRA COMMERCE</p><h1>Shipping & tax</h1><p className="hero-copy">Configure destination zones, shipping prices and tax rules used by checkout.</p></div><button className="button button-dark" onClick={()=>post({action:"initialize"})}>Initialize countries & currencies</button></div>
  {msg&&<p className="muted">{msg}</p>}{loading?<p>Loading…</p>:<>
   <section className="admin-card"><h2>Shipping zones</h2><p className="muted">Countries are grouped into zones. Add your actual shipping prices as rules.</p>{d.zones.map((z:any)=><div key={z.id} className="admin-row"><div><strong>{z.name}</strong><div className="muted">{z.countries.map((x:any)=>x.country.code).join(", ")}</div></div><span>{z.active?"Active":"Inactive"}</span></div>)}</section>
   <section className="admin-card"><h2>Add shipping rule</h2><form className="admin-grid" onSubmit={e=>{e.preventDefault();post({action:"shippingRule",...s})}}>
    <select value={s.zoneId} onChange={field(setS,s)("zoneId")} required><option value="">Select zone</option>{d.zones.map((z:any)=><option key={z.id} value={z.id}>{z.name}</option>)}</select><input value={s.name} onChange={field(setS,s)("name")} placeholder="Rule name" required/>
    <select value={s.shippingClass} onChange={field(setS,s)("shippingClass")}><option value="">All shipping classes</option>{classes.map(x=><option key={x}>{x}</option>)}</select><select value={s.supplierId} onChange={field(setS,s)("supplierId")}><option value="">All suppliers</option>{d.suppliers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
    <input type="number" min="0" step="0.01" value={s.price} onChange={field(setS,s)("price")} placeholder="Price" required/><input value={s.currency} onChange={field(setS,s)("currency")} placeholder="Currency" required/><input type="number" min="0" step="0.01" value={s.minWeight} onChange={field(setS,s)("minWeight")} placeholder="Min weight kg"/><input type="number" min="0" step="0.01" value={s.maxWeight} onChange={field(setS,s)("maxWeight")} placeholder="Max weight kg"/><input type="number" min="0" step="0.01" value={s.minOrderValue} onChange={field(setS,s)("minOrderValue")} placeholder="Min order value"/><input type="number" min="0" step="0.01" value={s.maxOrderValue} onChange={field(setS,s)("maxOrderValue")} placeholder="Max order value"/>
    <button className="button button-dark" type="submit">Add shipping rule</button></form>
    <div className="admin-list">{d.zones.flatMap((z:any)=>z.rules.map((r:any)=><div key={r.id} className="admin-row"><div><strong>{r.name}</strong><div className="muted">{z.name} · {r.shippingClass||"all classes"} · {r.price} {r.currency}</div></div><span>{r.active?"Active":"Inactive"}</span></div>))}</div>
   </section>
   <section className="admin-card"><h2>Tax rules</h2><p className="muted">Enter the tax rate applicable to each destination. Confirm applicable tax obligations before enabling a rule.</p><form className="admin-grid" onSubmit={e=>{e.preventDefault();post({action:"taxRule",...t})}}><select value={t.countryId} onChange={e=>setT({...t,countryId:e.target.value})} required><option value="">Select country</option>{d.countries.map((c:any)=><option key={c.id} value={c.id}>{c.name} ({c.code})</option>)}</select><input value={t.name} onChange={e=>setT({...t,name:e.target.value})} placeholder="Tax name" required/><input type="number" min="0" max="100" step="0.0001" value={t.rate} onChange={e=>setT({...t,rate:e.target.value})} placeholder="Rate %" required/><input value={t.taxClass} onChange={e=>setT({...t,taxClass:e.target.value})} placeholder="Tax class (optional)"/><button className="button button-dark" type="submit">Add tax rule</button></form><div className="admin-list">{d.taxes.map((x:any)=><div key={x.id} className="admin-row"><div><strong>{x.name}</strong><div className="muted">{x.country.name} · {x.rate}%{x.taxClass?" · "+x.taxClass:""}</div></div><span>{x.active?"Active":"Inactive"}</span></div>)}</div></section>
  </>}</div></main>
}