"use client";import{useEffect,useMemo,useState}from"react";
export default function ProductsClient(){const[p,setP]=useState<any[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState("ALL"),[type,setType]=useState("ALL"),[msg,setMsg]=useState(""),[busy,setBusy]=useState(true),[editing,setEditing]=useState<any|null>(null);
async function load(){setBusy(true);const r=await fetch("/api/admin/products");const j=await r.json();if(r.ok)setP(j.products||[]);else setMsg(j.error||"Unable to load products.");setBusy(false)}useEffect(()=>{load()},[]);
const rows=useMemo(()=>p.filter(x=>(status==="ALL"||x.status===status)&&(type==="ALL"||x.productType===type)&&(!q||x.name.toLowerCase().includes(q.toLowerCase())||x.sku.toLowerCase().includes(q.toLowerCase()))),[p,q,status,type]);
async function save(){if(!editing)return;setMsg("Saving…");const r=await fetch("/api/admin/products",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing)});const j=await r.json();if(r.ok){setP(x=>x.map(p=>p.id===editing.id?j.product:p));setEditing(null);setMsg("Product updated.")}else setMsg(j.error||"Update failed.")}
async function archive(id:string){if(!window.confirm("Archive this product? It will no longer be shown as active."))return;const r=await fetch("/api/admin/products?id="+encodeURIComponent(id),{method:"DELETE"});const j=await r.json();if(r.ok){setP(x=>x.map(p=>p.id===id?j.product:p));setMsg("Product archived.")}else setMsg(j.error||"Archive failed.")}
return <main className="section"><div className="container"><div className="admin-heading"><div><p className="eyebrow">MOTEVRA COMMERCE</p><h1>Products</h1><p className="hero-copy">Manage your catalogue, pricing, publishing status and fulfilment settings.</p></div><a className="button button-dark" href="/admin#add-product">Add product</a></div>
{msg&&<p className="muted">{msg}</p>}<div className="admin-filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name or SKU"/><select value={status} onChange={e=>setStatus(e.target.value)}><option>ALL</option><option>ACTIVE</option><option>DRAFT</option><option>ARCHIVED</option></select><select value={type} onChange={e=>setType(e.target.value)}><option>ALL</option><option>TYRE</option><option>WHEEL</option><option>ACCESSORY</option><option>AUTO_PART</option><option>BATTERY</option><option>ELECTRONICS</option><option>CAR_CARE</option><option>OTHER</option></select><button className="button" onClick={load}>Refresh</button></div>
{busy?<p>Loading…</p>:<div className="admin-list">{rows.map(x=><div className="admin-row" key={x.id}><div><strong>{x.name}</strong><div className="muted">{x.sku} · {x.productType} · {x.currency} {Number(x.price).toFixed(2)} · stock {x.stock} · {x.fulfillmentMethod}</div>{x.supplierProducts?.map((sp:any)=><div className="muted" key={sp.id}>Supplier: {sp.supplier.name} · cost {sp.supplierCurrency} {Number(sp.supplierCost).toFixed(2)}</div>)}</div><div className="admin-actions"><span>{x.status}</span><button className="button button-small" onClick={()=>setEditing({...x,price:Number(x.price),salePrice:x.salePrice==null?"":Number(x.salePrice),stock:x.stock})}>Edit</button>{x.status!=="ARCHIVED"&&<button className="button button-small" onClick={()=>archive(x.id)}>Archive</button>}</div></div>)}</div>}
{editing&&<div className="admin-card"><h2>Edit product</h2><div className="admin-grid"><input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/><input value={editing.sku} onChange={e=>setEditing({...editing,sku:e.target.value})}/><input type="number" step="0.01" value={editing.price} onChange={e=>setEditing({...editing,price:e.target.value})}/><input type="number" step="0.01" value={editing.salePrice} onChange={e=>setEditing({...editing,salePrice:e.target.value})}/><input type="number" min="0" value={editing.stock} onChange={e=>setEditing({...editing,stock:e.target.value})}/><select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option>DRAFT</option><option>ACTIVE</option><option>ARCHIVED</option></select><select value={editing.fulfillmentMethod} onChange={e=>setEditing({...editing,fulfillmentMethod:e.target.value})}><option>SELF</option><option>MANUAL</option><option>SUPPLIER_API</option></select><select value={editing.shippingClass} onChange={e=>setEditing({...editing,shippingClass:e.target.value})}><option>STANDARD</option><option>HEAVY</option><option>BATTERY</option><option>LIQUID</option><option>ELECTRONICS</option><option>TYRE</option><option>WHEEL</option><option>RESTRICTED</option></select></div><div className="admin-actions"><button className="button button-dark" onClick={save}>Save changes</button><button className="button" onClick={()=>setEditing(null)}>Cancel</button></div></div>}
</div></main>}