"use client";
import {useEffect,useMemo,useState} from "react";
export function AdminCategories(){
 const[categories,setCategories]=useState<any[]>([]),[name,setName]=useState(""),[parentId,setParentId]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[editing,setEditing]=useState<any>(null);
 const parents=useMemo(()=>categories.filter(c=>!c.parentId),[categories]);
 async function load(){const r=await fetch("/api/admin/categories");const j=await r.json();if(r.ok)setCategories(j.categories||[]);else setMsg(j.error||"Unable to load categories.")}
 useEffect(()=>{load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg("");try{const r=await fetch("/api/admin/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,parentId:parentId||null})});const j=await r.json();if(!r.ok)throw Error(j.error);setName("");setParentId("");await load();setMsg(parentId?"Subcategory created.":"Category created.");}catch(e){setMsg(e instanceof Error?e.message:"Unable to create category")}finally{setBusy(false)}}
 async function edit(e:React.FormEvent){e.preventDefault();if(!editing)return;setBusy(true);try{const r=await fetch("/api/admin/categories",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing)});const j=await r.json();if(!r.ok)throw Error(j.error);await load();setEditing(null);setMsg("Category updated.");}catch(e){setMsg(e instanceof Error?e.message:"Unable to update category")}finally{setBusy(false)}}
 async function remove(id:string,name:string){if(!window.confirm(`Delete category "${name}"? Only empty categories without subcategories can be deleted.`))return;setBusy(true);try{const r=await fetch("/api/admin/categories?id="+encodeURIComponent(id),{method:"DELETE"});const j=await r.json();if(!r.ok)throw Error(j.error);setCategories(x=>x.filter(c=>c.id!==id));setMsg("Category deleted.");}catch(e){setMsg(e instanceof Error?e.message:"Unable to delete category")}finally{setBusy(false)}}
 async function upload(id:string,file:File){setBusy(true);const fd=new FormData();fd.append("categoryId",id);fd.append("file",file);const r=await fetch("/api/admin/categories/image",{method:"POST",body:fd});const j=await r.json();if(!r.ok)setMsg(j.error||"Image upload failed.");else{setCategories(x=>x.map(c=>c.id===id?j.category:c));setMsg("Category image saved.");}setBusy(false)}
 return <main className="section"><div className="container"><div className="admin-heading"><div><p className="eyebrow">CATALOGUE</p><h1>Categories</h1><p className="hero-copy">Create top-level categories and subcategories for accurate storefront navigation and product filtering.</p></div></div>
 <form className="admin-card category-admin-form" onSubmit={create}><h2>Add category or subcategory</h2><div className="form-section-grid"><label className="admin-field"><span>Name *</span><input required value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Summer Tyres"/></label><label className="admin-field"><span>Parent category</span><select value={parentId} onChange={e=>setParentId(e.target.value)}><option value="">Top-level category</option>{parents.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="admin-form-actions"><button className="button button-dark" disabled={busy}>Create</button></div></div></form>
 {msg&&<p className="admin-message">{msg}</p>}
 <div className="admin-list-section"><div className="admin-list-heading"><div><p className="eyebrow">CATALOGUE TREE</p><h2>Categories & subcategories</h2></div><span>{parents.length} main · {categories.filter(c=>c.parentId).length} sub</span></div>
 <div className="category-admin-grid">{parents.map(c=><article className="category-admin-card" key={c.id}><div className="category-admin-preview">{c.imageUrl?<img src={c.imageUrl.startsWith("supabase://")?"/api/categories/image?ref="+encodeURIComponent(c.imageUrl):c.imageUrl} alt={c.name}/>:<span>No image</span>}</div><div><span className="eyebrow">{c._count?.products||0} PRODUCTS · MAIN CATEGORY</span><h3>{c.name}</h3><p>{c.slug}</p><div className="category-sub-list">{(c.children||[]).map((s:any)=><span key={s.id}>{s.name}</span>)}</div></div><div className="admin-actions"><button className="button button-small" type="button" disabled={busy} onClick={()=>setEditing({id:c.id,name:c.name,slug:c.slug,parentId:null})}>Edit</button><label className="button category-upload-button">Choose category image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" hidden disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(c.id,f);e.currentTarget.value=""}}/></label><button className="button button-small" type="button" disabled={busy} onClick={()=>remove(c.id,c.name)}>Delete</button></div></article>)}</div>
 <div className="category-admin-grid">{categories.filter(c=>c.parentId).map(c=><article className="category-admin-card" key={c.id}><div className="category-admin-preview">{c.imageUrl?<img src={c.imageUrl.startsWith("supabase://")?"/api/categories/image?ref="+encodeURIComponent(c.imageUrl):c.imageUrl} alt={c.name}/>:<span>No image</span>}</div><div><span className="eyebrow">SUBCATEGORY · {c.parent?.name||"—"}</span><h3>{c.name}</h3><p>{c.slug}</p></div><div className="admin-actions"><button className="button button-small" type="button" disabled={busy} onClick={()=>setEditing({id:c.id,name:c.name,slug:c.slug,parentId:c.parentId})}>Edit</button><label className="button category-upload-button">Choose image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" hidden disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(c.id,f);e.currentTarget.value=""}}/></label><button className="button button-small" type="button" disabled={busy} onClick={()=>remove(c.id,c.name)}>Delete</button></div></article>)}</div></div>
 {editing&&<div className="admin-modal-backdrop"><form className="admin-modal" onSubmit={edit}><h2>Edit category</h2><div className="admin-grid"><label className="admin-field"><span>Name</span><input value={editing.name||""} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label className="admin-field"><span>Slug</span><input value={editing.slug||""} onChange={e=>setEditing({...editing,slug:e.target.value})}/></label><label className="admin-field"><span>Parent category</span><select value={editing.parentId||""} onChange={e=>setEditing({...editing,parentId:e.target.value||null})}><option value="">Top-level category</option>{parents.filter(p=>p.id!==editing.id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className="admin-actions"><button className="button button-dark" disabled={busy}>Save</button><button className="button" type="button" onClick={()=>setEditing(null)}>Cancel</button></div></form></div>}
 </div></main>}
