"use client";import{useEffect,useState}from"react";
export function AdminProductForm(){const[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[type,setType]=useState("TYRE"),[suppliers,setSuppliers]=useState<any[]>([]),[fulfillment,setFulfillment]=useState("SELF");
useEffect(()=>{fetch("/api/admin/suppliers").then(r=>r.ok?r.json():null).then(j=>{if(j)setSuppliers(j.suppliers||[])}).catch(()=>{})},[]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const d=Object.fromEntries(new FormData(e.currentTarget)),images=String(d.images||"").split("\n").map(x=>x.trim()).filter(Boolean);const r=await fetch("/api/admin/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...d,images,runFlat:d.runFlat==="on"})}),j=await r.json();if(r.ok){setMsg("Product created.");e.currentTarget.reset();setFulfillment("SELF");setTimeout(()=>location.reload(),500)}else setMsg(j.error||"Unable to create product.");setBusy(false)}
return <form id="add-product" className="admin-form" onSubmit={submit}><div className="admin-form-heading"><p className="eyebrow">CATALOGUE</p><h2>Add product</h2><p className="muted">Products can be sold from your own local stock, fulfilled manually, or linked to a supplier.</p></div>
<input name="name" placeholder="Product name" required/><input name="sku" placeholder="SKU" required/><input name="brand" placeholder="Brand"/><input name="category" placeholder="Category"/>
<div className="form-grid"><select name="productType" value={type} onChange={e=>setType(e.target.value)}><option>TYRE</option><option>WHEEL</option><option>ACCESSORY</option><option>AUTO_PART</option><option>BATTERY</option><option>ELECTRONICS</option><option>CAR_CARE</option><option>OTHER</option></select>
<select name="fulfillmentMethod" value={fulfillment} onChange={e=>setFulfillment(e.target.value)}><option value="SELF">My own stock / local product</option><option value="MANUAL">Supplier — manual fulfillment</option><option value="SUPPLIER_API">Supplier — API fulfillment</option></select></div>
{fulfillment!=="SELF"&&<div className="form-grid"><select name="supplierId" required><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name} ({s.type})</option>)}</select><input name="supplierCost" type="number" min="0" step="0.01" placeholder="Supplier cost" required/><input name="supplierCurrency" defaultValue="USD" placeholder="Supplier currency"/><input name="externalProductId" placeholder="Supplier product ID (optional)"/><input name="externalSku" placeholder="Supplier SKU (optional)"/></div>}
<textarea name="description" placeholder="Product description"/><div className="form-grid"><input name="price" type="number" step="0.01" min="0" placeholder="Selling price" required/><input name="salePrice" type="number" step="0.01" min="0" placeholder="Sale price"/><input name="currency" defaultValue="USD" placeholder="Currency"/><input name="stock" type="number" min="0" placeholder="Stock" defaultValue="0"/><input name="weight" type="number" min="0" step="0.001" placeholder="Weight kg"/></div>
<div className="form-grid"><select name="shippingClass" defaultValue="STANDARD"><option value="STANDARD">Standard shipping</option><option value="HEAVY">Heavy</option><option value="BATTERY">Battery</option><option value="LIQUID">Liquid</option><option value="ELECTRONICS">Electronics</option><option value="TYRE">Tyre</option><option value="WHEEL">Wheel</option><option value="RESTRICTED">Restricted</option></select></div>
{type==="TYRE"&&<div className="tyre-fields"><strong>Tyre specifications</strong><div className="form-grid"><input name="width" type="number" placeholder="Width e.g. 205"/><input name="aspectRatio" type="number" placeholder="Aspect ratio e.g. 55"/><input name="rimSize" type="number" placeholder="Rim e.g. 16"/><input name="loadIndex" type="number" placeholder="Load index e.g. 91"/><input name="speedRating" placeholder="Speed rating e.g. V"/><select name="season"><option value="">Season</option><option value="SUMMER">Summer</option><option value="WINTER">Winter</option><option value="ALL_SEASON">All season</option></select></div><label className="check"><input name="runFlat" type="checkbox"/> Run-flat</label></div>}
<textarea name="images" placeholder="Professional image URLs — one per line"/><select name="status" defaultValue="DRAFT"><option value="DRAFT">Save as draft</option><option value="ACTIVE">Publish now</option></select><button className="button button-dark" disabled={busy}>{busy?"Saving…":"Create product"}</button>{msg&&<p className="muted">{msg}</p>}</form>}