"use client";import{useEffect,useMemo,useState}from"react";import Link from"next/link";
type Variant={id:string;name:string;slug:string;yearFrom:number;yearTo:number|null;engine:string|null;bodyType:string|null};type Make={id:string;name:string;slug:string;models:{id:string;name:string;slug:string;variants:Variant[]}[]};type Product={id:string;name:string;slug:string;price:number|null;salePrice:number|null;images:{url:string}[];brand?:{name:string}|null;tyre?:{size?:{label:string}|null}|null};
const sizes=["175/65 R14","185/65 R15","195/65 R15","205/55 R16","215/60 R17","225/45 R17","235/55 R18","245/45 R18","265/65 R17"];
export function TyreFinder(){const[mode,setMode]=useState<"vehicle"|"size">("vehicle"),[makes,setMakes]=useState<Make[]>([]),[make,setMake]=useState(""),[model,setModel]=useState(""),[variantId,setVariantId]=useState(""),[size,setSize]=useState(""),[message,setMessage]=useState(""),[results,setResults]=useState<Product[]>([]),[loading,setLoading]=useState(false);
useEffect(()=>{fetch("/api/vehicles").then(r=>r.json()).then(d=>setMakes(d.makes??[])).catch(()=>setMakes([]))},[]);
const selected=makes.find(m=>m.slug===make),selectedModel=selected?.models.find(m=>m.slug===model),variants=selectedModel?.variants??[];const selectedVariant=variants.find(v=>v.id===variantId);
function resetResults(){setResults([]);setMessage("")}
function search(){const params=new URLSearchParams();if(mode==="size"){const match=size.match(/^(\d+)\/(\d+)\s+R(\d+)$/);if(!match){setMessage("Please select a tyre size.");return}params.set("width",match[1]);params.set("aspectRatio",match[2]);params.set("rimSize",match[3])}else{if(!variantId){setMessage("Please select your vehicle variant.");return}params.set("variantId",variantId)}setLoading(true);setMessage("Finding compatible tyres…");setResults([]);fetch("/api/tyre-finder?"+params.toString()).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Search failed");return d}).then(d=>{setResults(d.products??[]);setMessage(d.products?.length?`${d.products.length} compatible tyre option(s) found.`:"No compatible tyres found in the current catalogue.")}).catch(()=>setMessage("Tyre catalogue is unavailable right now. Please try again.")).finally(()=>setLoading(false))}
function selectMode(next:"vehicle"|"size"){setMode(next);resetResults()}
return <div className="finder-panel"><div className="finder-tabs"><button type="button" className={"finder-tab"+(mode==="vehicle"?" active":"")} onClick={()=>selectMode("vehicle")}>By vehicle</button><button type="button" className={"finder-tab"+(mode==="size"?" active":"")} onClick={()=>selectMode("size")}>By size</button></div>
{mode==="vehicle"?<div className="finder-fields"><select value={make} onChange={e=>{setMake(e.target.value);setModel("");setVariantId("");resetResults()}} aria-label="Vehicle make"><option value="">Make</option>{makes.map(m=><option key={m.id} value={m.slug}>{m.name}</option>)}</select><select value={model} onChange={e=>{setModel(e.target.value);setVariantId("");resetResults()}} disabled={!selected} aria-label="Vehicle model"><option value="">Model</option>{selected?.models.map(m=><option key={m.id} value={m.slug}>{m.name}</option>)}</select><select value={variantId} onChange={e=>{setVariantId(e.target.value);resetResults()}} disabled={!selectedModel} aria-label="Vehicle year and variant"><option value="">Year / variant / engine</option>{variants.map(v=><option key={v.id} value={v.id}>{v.name} · {v.yearFrom}{v.yearTo?"–"+v.yearTo:"+"}{v.engine?" · "+v.engine:""}</option>)}</select></div>:<div className="finder-fields"><select value={size} onChange={e=>{setSize(e.target.value);resetResults()}} aria-label="Tyre size"><option value="">Tyre size</option>{sizes.map(item=><option key={item} value={item}>{item}</option>)}</select></div>}
<button className="button button-accent" type="button" onClick={search} disabled={loading}>{loading?"Searching…":mode==="size"?"Find tyres by size":"Find compatible tyres"}</button>{message&&<p className="finder-message">{message}</p>}
{selectedVariant&&mode==="vehicle"&&<p className="finder-message">{selectedVariant.bodyType?selectedVariant.bodyType+" · ":""}{selectedVariant.engine||"Vehicle variant selected"} · {selectedVariant.yearFrom}{selectedVariant.yearTo?"–"+selectedVariant.yearTo:"+"}</p>}
{results.length>0&&<div className="finder-results">{results.slice(0,8).map(p=><Link className="finder-result" key={p.id} href={"/product/"+p.slug}><span><strong>{p.name}</strong><small>{p.brand?.name?p.brand.name+" · ":""}{p.tyre?.size?.label||"Tyre"}</small></span><b>{p.salePrice??p.price??""}</b></Link>)}</div>}
{mode==="size"&&size&&message.includes("found")?<Link className="finder-results-link" href={"/shop?size="+encodeURIComponent(size)}>View matching tyres →</Link>:null}</div>}