"use client";import{useEffect,useMemo,useState}from"react";
const bodies=["SEDAN","HATCHBACK","SUV","COUPE","WAGON","PICKUP","VAN","MPV","OTHER"];
export default function FitmentClient(){
const[d,setD]=useState<any>({makes:[],sizes:[],products:[],fitments:[],tyreFitments:[]}),[msg,setMsg]=useState(""),[busy,setBusy]=useState(true);
const[make,setMake]=useState(""),[model,setModel]=useState(""),[variant,setVariant]=useState<any>({modelId:"",name:"",yearFrom:"",yearTo:"",engine:"",bodyType:""}),[size,setSize]=useState({width:"",aspectRatio:"",rimSize:""}),[tf,setTf]=useState({vehicleVariantId:"",tyreSizeId:"",position:"",notes:""}),[pf,setPf]=useState({productId:"",vehicleVariantId:"",notes:""});
async function load(){setBusy(true);const r=await fetch("/api/admin/fitment");const j=await r.json();if(r.ok)setD(j);else setMsg(j.error||"Unable to load fitment.");setBusy(false)}useEffect(()=>{load()},[]);
const models=useMemo(()=>d.makes.flatMap((m:any)=>m.models.map((x:any)=>({...x,makeName:m.name}))),[d.makes]);
const variants=useMemo(()=>models.flatMap((m:any)=>m.variants.map((v:any)=>({...v,modelName:m.name,makeName:m.makeName}))),[models]);
async function post(body:any){setMsg("Saving…");const r=await fetch("/api/admin/fitment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(r.ok){setMsg("Saved.");load()}else setMsg(j.error||"Save failed.")}
return <main className="section"><div className="container"><div className="admin-heading"><div><p className="eyebrow">MOTEVRA FITMENT</p><h1>Vehicles & compatibility</h1><p className="hero-copy">Build the vehicle catalogue and connect tyres, wheels and parts to compatible vehicles.</p></div><a className="button button-dark" href="/admin">Back to dashboard</a></div>{msg&&<p className="muted">{msg}</p>}
<section className="admin-card"><h2>Vehicle catalogue</h2><div className="admin-grid"><input value={make} onChange={e=>setMake(e.target.value)} placeholder="New make, e.g. Toyota"/><button className="button" onClick={()=>make&&post({action:"make",name:make})}>Add make</button></div>
<div className="admin-grid"><select value={variant.modelId} onChange={e=>setVariant({...variant,modelId:e.target.value})}><option value="">Select model</option>{models.map((m:any)=><option key={m.id} value={m.id}>{m.makeName} — {m.name}</option>)}</select><input value={model} onChange={e=>setModel(e.target.value)} placeholder="New model"/><button className="button" onClick={()=>{const m=d.makes.find((x:any)=>x.name===make);if(model&&m)post({action:"model",makeId:m.id,name:model})}}>Add model to selected make</button></div>
<div className="admin-grid"><select value={variant.modelId} onChange={e=>setVariant({...variant,modelId:e.target.value})}><option value="">Model for variant</option>{models.map((m:any)=><option key={m.id} value={m.id}>{m.makeName} — {m.name}</option>)}</select><input value={variant.name} onChange={e=>setVariant({...variant,name:e.target.value})} placeholder="Variant, e.g. 1.3 GLi"/><input type="number" value={variant.yearFrom} onChange={e=>setVariant({...variant,yearFrom:e.target.value})} placeholder="From year"/><input type="number" value={variant.yearTo} onChange={e=>setVariant({...variant,yearTo:e.target.value})} placeholder="To year"/><input value={variant.engine} onChange={e=>setVariant({...variant,engine:e.target.value})} placeholder="Engine"/><select value={variant.bodyType} onChange={e=>setVariant({...variant,bodyType:e.target.value})}><option value="">Body type</option>{bodies.map(x=><option key={x}>{x}</option>)}</select><button className="button button-dark" onClick={()=>post({action:"variant",...variant})}>Add vehicle variant</button></div></section>
<section className="admin-card"><h2>Tyre sizes</h2><div className="admin-grid"><input type="number" value={size.width} onChange={e=>setSize({...size,width:e.target.value})} placeholder="Width e.g. 205"/><input type="number" value={size.aspectRatio} onChange={e=>setSize({...size,aspectRatio:e.target.value})} placeholder="Aspect ratio e.g. 55"/><input type="number" value={size.rimSize} onChange={e=>setSize({...size,rimSize:e.target.value})} placeholder="Rim e.g. 16"/><button className="button" onClick={()=>post({action:"size",...size})}>Add tyre size</button></div><p className="muted">{d.sizes.map((x:any)=>x.label).join(" · ")||"No sizes yet."}</p></section>
<section className="admin-card"><h2>Tyre fitment</h2><div className="admin-grid"><select value={tf.vehicleVariantId} onChange={e=>setTf({...tf,vehicleVariantId:e.target.value})}><option value="">Vehicle variant</option>{variants.map((v:any)=><option key={v.id} value={v.id}>{v.makeName} {v.modelName} {v.name} ({v.yearFrom}{v.yearTo?"–"+v.yearTo:"+"})</option>)}</select><select value={tf.tyreSizeId} onChange={e=>setTf({...tf,tyreSizeId:e.target.value})}><option value="">Tyre size</option>{d.sizes.map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input value={tf.position} onChange={e=>setTf({...tf,position:e.target.value})} placeholder="Position e.g. Front / Rear"/><input value={tf.notes} onChange={e=>setTf({...tf,notes:e.target.value})} placeholder="Notes"/><button className="button button-dark" onClick={()=>post({action:"tyreFitment",...tf})}>Save tyre fitment</button></div>
<div className="admin-list">{d.tyreFitments.map((x:any)=><div className="admin-row" key={x.id}><div><strong>{x.vehicleVariant.model.make.name} {x.vehicleVariant.model.name} {x.vehicleVariant.name}</strong><div className="muted">{x.tyreSize.label}{x.position?" · "+x.position:""}{x.isOriginal?" · OEM fitment":""}</div></div></div>)}</div></section>
<section className="admin-card"><h2>Product compatibility</h2><div className="admin-grid"><select value={pf.productId} onChange={e=>setPf({...pf,productId:e.target.value})}><option value="">Product</option>{d.products.map((x:any)=><option key={x.id} value={x.id}>{x.name} ({x.sku})</option>)}</select><select value={pf.vehicleVariantId} onChange={e=>setPf({...pf,vehicleVariantId:e.target.value})}><option value="">Vehicle variant</option>{variants.map((v:any)=><option key={v.id} value={v.id}>{v.makeName} {v.modelName} {v.name}</option>)}</select><input value={pf.notes} onChange={e=>setPf({...pf,notes:e.target.value})} placeholder="Compatibility notes"/><button className="button button-dark" onClick={()=>post({action:"productFitment",...pf})}>Link product</button></div>
<div className="admin-list">{d.fitments.map((x:any)=><div className="admin-row" key={x.id}><div><strong>{x.product.name}</strong><div className="muted">{x.vehicleVariant.model.make.name} {x.vehicleVariant.model.name} {x.vehicleVariant.name}{x.notes?" · "+x.notes:""}</div></div></div>)}</div></section>
{busy&&<p>Loading…</p>}</div></main>}